#!/usr/bin/env python3
"""SYNTHETIC. Builds Sources/MemoryCore/PreviewSampleFixture.swift for the "DayDream Preview" build (--preview-sample).

Inputs (all made up; no real data):
  examples/week.json               a made-up week of a made-up founder ("Riley", app "Tallybird"), from make_week.py
  examples/work/after/memory.sqlite that week run through summaries/v3 (prompt7 + validator9) with the pinned local
                                   writer model (examples/run-after.sh): its moment notes are real model outputs.
Output: one Swift file holding the evidence rows and the moment notes (title, bullets, cited action ids) as JSON.
The app re-dates the rows to the last seven days at launch and commits the notes through the normal core checks.

Usage: python3 scripts/preview/make-preview-fixture.py <examples dir> <output .swift>"""
import json, sqlite3, sys
from pathlib import Path

examples, out = Path(sys.argv[1]), Path(sys.argv[2])
week = json.loads((examples / "week.json").read_text())
# The original fabricated week predates the field metadata. Its explicitly
# addressed Messages body units must carry their modeled body proof after B2;
# production captures never get this synthetic-only compatibility annotation.
for evidence in week["evidence"]:
    unit = evidence.get("captureProvenance", {}).get("unit", {})
    if (evidence.get("synthetic") is True and evidence.get("bundle") == "com.apple.MobileSMS"
            and evidence.get("kind") == "keyboard.text_input" and unit.get("surface") == "text"
            and unit.get("to") and "field" not in unit):
        unit["field"] = "message"
db = sqlite3.connect("file:%s?mode=ro" % (examples / "work/after/memory.sqlite"), uri=True)
notes = []
for (body,) in db.execute("SELECT body FROM generated_notes g WHERE version=(SELECT max(version) FROM generated_notes h WHERE h.id=g.id) AND id LIKE 'activity_%' ORDER BY id"):
    n = json.loads(body)
    o = n["output"]
    notes.append({"actions": sorted(n["actionIDs"]), "title": o["title"],
                  "bullets": [{"text": b["text"], "actions": b["actionIDs"], "assertion": b["assertion"]} for b in o["bullets"]],
                  "generator": o["generator"], "generatorVersion": o["generatorVersion"]})
fixture = {"about": "SYNTHETIC preview week: made-up person, app, messages and sites. Moment notes written by the local writer model (prompt7 + validator9) on this same made-up evidence.",
           "timezone": week["timezone"], "evidence": week["evidence"], "notes": notes}
text = json.dumps(fixture, separators=(",", ":"), sort_keys=True, ensure_ascii=False)
assert '"##' not in text
out.write_text("// GENERATED by scripts/preview/make-preview-fixture.py. SYNTHETIC: a made-up week (no real data).\n"
               "// Evidence from summaries-v3/examples/week.json; moment notes from the same week run through the local writer model.\n"
               "enum PreviewSampleFixture {\n    static let json = ##\"" + text + "\"##\n}\n")
print("evidence", len(week["evidence"]), "notes", len(notes), "bytes", len(text))
