"""claude/rel-017c: keeps Sources/MemoryCore/AgentSkillFiles.swift, the copy of skills/daydream that Connect writes for
ChatGPT, the same as the skill in the repo.

  python3 scripts/agent-skill-embed.py          # rewrites the Swift file from skills/daydream
  python3 scripts/agent-skill-embed.py --check  # fails when the two differ (the headless suite runs this)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL = ROOT / 'skills/daydream'
OUT = ROOT / 'Sources/MemoryCore/AgentSkillFiles.swift'


def render():
    files = sorted(p for p in SKILL.rglob('*') if p.is_file() and not p.name.startswith('.'))
    files.sort(key=lambda p: (p.name != 'SKILL.md', str(p.relative_to(SKILL))))
    parts = []
    for path in files:
        text = path.read_text()
        assert '"""#' not in text and '\\#' not in text, f'{path}: would end or interpolate the raw string'
        # A raw multi-line literal drops the last line break before its closing delimiter: add one back.
        parts.append(f'        ("{path.relative_to(SKILL)}", #"""\n{text}\n"""#),')
    return ('// Generated by scripts/agent-skill-embed.py from skills/daydream. Don\'t edit by hand.\n\n'
            'enum AgentSkillFiles {\n'
            '    /// Each file of DayDream\'s Agent Skill, by its path inside the skill folder.\n'
            '    static let files: [(path: String, text: String)] = [\n' + '\n'.join(parts) + '\n    ]\n}\n')


if __name__ == '__main__':
    want = render()
    if '--check' in sys.argv:
        have = OUT.read_text() if OUT.exists() else ''
        if have != want:
            print('FAIL AgentSkillFiles.swift differs from skills/daydream: run python3 scripts/agent-skill-embed.py')
            sys.exit(1)
        print('PASS AgentSkillFiles.swift matches skills/daydream')
    else:
        OUT.write_text(want)
        print('wrote', OUT.relative_to(ROOT))
